# -*- coding: utf-8 -*-
"""01_pytorch_workflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11kxSMJ-EN5EuW2PxyrVbn5vaUGwxpnCj

## PyTorch Workflow
"""

import torch

weight = 0.7
bias = 0.3
start = 0
end = 1
step = 0.02

X = torch.arange(start, end, step).unsqueeze(dim=1)
X[:10], X.shape

y = weight * X + bias
y[:10], y.shape

"""## Splitting data into training and testing sets"""

train_split = int(0.8 * len(X))
train_split

X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]

len(X_test), len(X_train), len(y_test), len(y_train)

"""## Visualizing our data"""

import matplotlib.pyplot as plt

def plot_predictions(train_data=X_train,train_labels=y_train,test_data=X_test,test_labels=y_test,predictions=None):
  plt.figure(figsize=(10, 7))

  # Traing data in blue
  plt.scatter(train_data, train_labels, c="b", s=8, label="Training data")

  # Testing data in green
  plt.scatter(test_data, test_labels, c="g", s=8, label="Testing data")

  if predictions is not None:
    plt.scatter(test_data, predictions, c="r", s=8, label="Predictions")

  plt.legend(prop={ "size": 14 })

plot_predictions()

"""## Creating my first PyTorch Model"""

from torch import nn

class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()

    # Start with random weights and bias and try to adjust it to the ideal values
    self.weights = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))

    self.bias = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))

  # forward method to define the computation in the model
  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return self.weights * x + self.bias

"""## Checking our PyTorch model"""

torch.manual_seed(42)

model_0 = LinearRegressionModel()
list(model_0.parameters())

model_0.state_dict()

"""## Making predictions with our model"""

with torch.inference_mode():
  y_preds = model_0(X_test)

plot_predictions(predictions=y_preds)

"""## Setting up a loss function and optimizer"""

loss_fn = nn.L1Loss()

# Stochastic Gradient Descent
optimizer = torch.optim.SGD(params=model_0.parameters(),
                            lr=0.0005) # Learning rate

"""## Building a training and a testing loop"""

epochs = 10000

epochs_count = []
loss_values = []
test_loss_values = []

for epoch in range(epochs):
  model_0.train() # Training mode

  # 1. Forward pass (make predictions)
  y_pred = model_0(X_train)

  # 2. Calculate the loss
  loss = loss_fn(y_pred, y_train)

  # 3. Gradient zero grad (Zero the gradients)
  optimizer.zero_grad()

  # 4. Loss backward ( Backpropagation )
  loss.backward()

  # 5. Gradient step ( Perform Gradient Descent )
  optimizer.step()

  # Testing
  model_0.eval()
  with torch.inference_mode():
    test_pred = model_0(X_test)
    test_loss = loss_fn(test_pred, y_test)

  if epoch % 1000 == 0:
    print(f"Epoch: {epoch} | Loss: {loss} | Test loss: {test_loss}")
    print(model_0.state_dict())
    epochs_count.append(epoch)
    loss_values.append(loss)
    test_loss_values.append(test_loss)

with torch.inference_mode():
  y_preds_test = model_0(X_test)

plot_predictions(predictions=y_preds_test)

# Plot the loss curves

loss_ndarray = torch.tensor(loss_values).detach().numpy()
test_loss_ndarray = torch.tensor(test_loss_values).detach().numpy()

plt.plot(epochs_count, loss_ndarray, label="Training loss")
plt.plot(epochs_count, test_loss_ndarray, label="Testing loss")
plt.title("Training and Testing loss throughout the epochs")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()

"""## Saving a model"""

from pathlib import Path

MODELS_DIR_PATH = Path("models")
MODELS_DIR_PATH.mkdir(parents=True, exist_ok=True)

MODEL_PATH = MODELS_DIR_PATH / "01_pytorch_workflow_model_0.pth"

torch.save(obj=model_0.state_dict(), f=MODEL_PATH)

"""## Loading a model"""

loaded_model_0 = LinearRegressionModel()

loaded_model_0.load_state_dict(torch.load(f=MODEL_PATH))

with torch.inference_mode():
  loaded_model_preds = loaded_model_0(X_test)

y_preds_test == loaded_model_preds