# -*- coding: utf-8 -*-
"""00_pytorch_fundamentals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAa7e6-3Z7kP8nXc7ZZVR75TcaHAa4Go

## PyTorch Fundamentals
"""

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

#scalar
scalar = torch.tensor(7)
scalar

scalar.ndim

scalar.item()

#vector
vector = torch.tensor([1, 5])
vector

vector.ndim

vector.shape

#MATRIX
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])
MATRIX

MATRIX.ndim

MATRIX.shape

#TENSOR
TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [1, 4, 9],
        [16, 25, 36],
        [49, 64, 81]
    ]
])
TENSOR

TENSOR.ndim

TENSOR.shape

TENSOR[0]

"""## Random Tensors"""

rand_image_size_tensor = torch.rand(size=(3, 224, 224))
rand_image_size_tensor.shape, rand_image_size_tensor.ndim

"""## Zeros and Ones:"""

zeros = torch.zeros(3, 4)
zeros

ones = torch.ones(3, 4)
ones

ones.dtype

"""## Range of Tensors and tensors-like"""

torch.arange(start=0, end=1000, step=77)

"""## Tensor Datatypes"""

tensor_float_32 = torch.tensor([3.0, 4.5, 6.7],
                               dtype=torch.float32, # Data Type
                               device="cpu", # What device is your tensor on
                               requires_grad=False # Whether or not to track the gradients with this tensor operations
                               )
tensor_float_32

tensor_float_16 = tensor_float_32.type(torch.float16)
tensor_float_16.dtype

"""## Manipulating Tensors"""

tensor = torch.rand(3)
tensor

# Add
tensor + tensor

# Sub
tensor - 3

# Mul
tensor * tensor

# Div
tensor / tensor

# Matrix Multiplication
torch.matmul(tensor, tensor)

"""## Transpose"""

MATRIX = torch.tensor([[1, 2], [3, 4], [5, 6]])
MATRIX, MATRIX.T

"""## Tensor Aggregation"""

x = torch.arange(0, 100, 2.5)

x.min(), x.max(), x.mean(), x.sum()

# Finding the position of the min and the max values
x.argmin(), x.argmax()

"""## Reshaping, Viewing and Stacking"""

y = torch.arange(1, 41)
y

y_reshaped = y.reshape(10, 4)
y_reshaped

z = y.view(4, 10) # It creates a copy of the tensor with a different shape, but sharing the same memory
z

z[:, 0] = 100 # It changes the original tensor 'y'
z, y

z_stacked = torch.stack([z, z, z], dim=0)
z_stacked

z_stacked = torch.stack([z, z, z], dim=1)
z_stacked

"""## Squeezing, Unsqueezing and Permuting"""

x = torch.rand(3, 1, 6)
x

y = torch.squeeze(x)
y

z = torch.unsqueeze(y, dim=0)
z, z.shape

"""## PyTorch and NumPy"""

numpy_arr = np.arange(1, 20, 2.5)
numpy_arr

pytorch_tensor = torch.from_numpy(numpy_arr)
pytorch_tensor

t = torch.arange(0, 200, 20)
t

ndarr = t.numpy()
ndarr

""" !nvidia-smi """

"""## GPU access with PyTorch"""

torch.cuda.is_available()

device = "cuda" if torch.cuda.is_available() else "cpu"

torch.cuda.device_count()

tensor_on_cpu = torch.arange(0, 10)
tensor_on_cpu.device

tensor_on_gpu = tensor_on_cpu.to(device)
tensor_on_gpu.device

backing_to_cpu = tensor_on_gpu.cpu()
backing_to_cpu.device